"""Monkey-patches Django permission codenames to use CRUDL naming conventions."""

# You shouldn't use anything from this module directly, but this is needed for the docs.
__all__ = (
    "get_builtin_permissions",
    "get_permission_codename",
    "permission_names_mapping",
)

# Must be imported in your project settings.py in order for things
# to get patched before they are used to create permissions.

# Patch get_permission_codename, so that it converts add, view, and change into create, read and update respectively.
# This appears to be the only way we can change the history table permissions, without patching more things.
from django.conf import settings
from django.contrib import auth


auth.django_get_permission_codename = auth.get_permission_codename

permission_names_mapping = settings.PERMISSION_NAMES_MAPPING


def get_permission_codename(action, opts):
    """
    Return the codename of the permission for the specified action, in the crud style.
    add = create
    view = read
    change = update
    delete doesn't change
    list is new
    """
    action = permission_names_mapping.get(action, action)
    return auth.django_get_permission_codename(action, opts)


auth.get_permission_codename = get_permission_codename


# Patch get_builtin_permissions, so that it converts add, view, and change into create, read and update respectively.
# This appears to be the only way we can change the history table permissions, without patching more things.
from django.contrib.auth import management  # noqa E402


def get_builtin_permissions(opts):
    """
    Return (codename, name) for all autogenerated permissions, in the crud style.
    add = create
    view = read
    change = update
    delete doesn't change
    list is new

    This is a customized django function, since we need to update the action name within a loop.
    https://github.com/django/django/blob/f302343380c77e1eb5dab3b64dd70895a95926ca/django/contrib/auth/management/__init__.py#L22-L35
    """
    perms = []
    for action in opts.default_permissions:
        action = permission_names_mapping.get(action, action)
        perm = (
            get_permission_codename(action, opts),
            f"Can {action} {opts.verbose_name_raw}",
        )
        # Make sure we don't add the same perm in the list twice, which can happen if older sites map list to view.
        # create_permissions in django would then try to create the
        # same permission twice, and get a duplicate key violation.
        if perm not in perms:
            perms.append(perm)
    return perms


management._get_builtin_permissions = get_builtin_permissions

# We also need to patch the perms_map in vueda\core\permissions.py and
# vueda\workflow\permissions.py, if the permissions are not set to the default.
if (
    "add" not in permission_names_mapping
    and "add" in permission_names_mapping.values()
    or "change" not in permission_names_mapping
    and "change" in permission_names_mapping.values()
    or "view" not in permission_names_mapping
    and "view" in permission_names_mapping.values()
):
    from vueda.core.permissions import ObjectPermissions

    if "vueda.workflow" in settings.INSTALLED_APPS:
        from vueda.workflow.permissions import WorkflowObjectPermissions

if "add" not in permission_names_mapping and "add" in permission_names_mapping.values():
    ObjectPermissions.perms_map["POST"] = ["%(app_label)s.add_%(model_name)s"]
    if "vueda.workflow" in settings.INSTALLED_APPS:
        WorkflowObjectPermissions.perms_map["POST"] = ["%(app_label)s.add_%(model_name)s"]

if "change" not in permission_names_mapping and "change" in permission_names_mapping.values():
    ObjectPermissions.perms_map["PUT"] = ["%(app_label)s.change_%(model_name)s"]
    ObjectPermissions.perms_map["PATCH"] = ["%(app_label)s.change_%(model_name)s"]
    if "vueda.workflow" in settings.INSTALLED_APPS:
        WorkflowObjectPermissions.perms_map["PUT"] = ["%(app_label)s.change_%(model_name)s"]
        WorkflowObjectPermissions.perms_map["PATCH"] = ["%(app_label)s.change_%(model_name)s"]

if "view" not in permission_names_mapping and "view" in permission_names_mapping.values():
    ObjectPermissions.perms_map["GET"] = ["%(app_label)s.view_%(model_name)s"]
    if "vueda.workflow" in settings.INSTALLED_APPS:
        WorkflowObjectPermissions.perms_map["GET"] = ["%(app_label)s.view_%(model_name)s"]
